package com.darwinsys.regex_regress;

/* AllTests - generated by Ian Darwin's alltest script */

import org.junit.runner.RunWith;
import org.junit.runners.Suite;
import org.junit.runners.Suite.SuiteClasses;

@RunWith(value=Suite.class)
@SuiteClasses(value={
	RETest.class,
	RunScriptedTests.class,
})
public class AllTests {
	// No Code Needed
}

